var players = [{
  "id": 0,
  "guid": "aa4a0364-7dfa-4ca5-bcb8-b5d3eaabdaf1",
  "isActive": false,
  "balance": "$2,262.00",
  "picture": "http://placehold.it/64x64",
  "age": 36,
  "name": "Horne Graves",
  "gender": "male",
  "company": "Amtas",
  "position": "center",
  "sdn_games": 81,
  "sdn_wins": 33,
  "fairplayer": 57,
  "king_of_court": 100,
  "level": "Social",
  "email": "hornegraves@amtas.com",
  "phone": "+1 (957) 429-2304",
  "address": "257 India Street, Barrelville, Pennsylvania, 5320",
  "about": "In sint elit cillum deserunt officia. Ex velit laborum ipsum et. Aliquip id in tempor commodo. Tempor ipsum ea officia magna incididunt id velit consequat culpa in qui do elit. Eu non pariatur ut commodo id aliqua laboris tempor incididunt sunt quis.\r\n",
  "registered": "2006-06-01T10:04:43 -06:-30",
  "latitude": 67.874913,
  "longitude": 116.747266
}, {
  "id": 1,
  "guid": "0c589fe0-62e1-4929-a9cd-40cce9638a7b",
  "isActive": false,
  "balance": "$1,151.00",
  "picture": "http://placehold.it/64x64",
  "age": 38,
  "name": "Rutledge Stevens",
  "gender": "male",
  "company": "Geostele",
  "position": "guard",
  "sdn_games": 84,
  "sdn_wins": 0,
  "fairplayer": 69,
  "king_of_court": 21,
  "level": "Social",
  "email": "rutledgestevens@geostele.com",
  "phone": "+1 (854) 571-3080",
  "address": "491 Burnett Street, Grimsley, Rhode Island, 8644",
  "about": "Est amet id officia eu. Eiusmod anim labore laboris fugiat est nulla ipsum dolor sunt elit incididunt dolor. Adipisicing deserunt et aute aliqua laboris excepteur proident eu occaecat culpa esse est laborum occaecat. Velit reprehenderit proident occaecat anim eu est aliqua ad. Lorem ut dolore incididunt sit duis sit consequat. Do eiusmod culpa veniam do irure cupidatat dolor. Aliqua sunt sunt culpa irure veniam in enim officia.\r\n",
  "registered": "2005-12-04T07:17:04 -06:-30",
  "latitude": -85.879615,
  "longitude": -92.510298
}, {
  "id": 2,
  "guid": "c6a023ad-f4bd-4d85-9660-718a7600169c",
  "isActive": false,
  "balance": "$3,918.00",
  "picture": "http://placehold.it/64x64",
  "age": 34,
  "name": "Brewer Norman",
  "gender": "male",
  "company": "Quarex",
  "position": "guard",
  "sdn_games": 87,
  "sdn_wins": 44,
  "fairplayer": 44,
  "king_of_court": 100,
  "level": "Social",
  "email": "brewernorman@quarex.com",
  "phone": "+1 (814) 532-2846",
  "address": "913 Everit Street, Richville, Oklahoma, 6341",
  "about": "Ipsum culpa quis Lorem nulla. Dolore elit minim laborum est magna cillum. Adipisicing excepteur irure sit aliquip nostrud labore dolor non in reprehenderit sit anim velit. Velit aliqua Lorem tempor qui mollit commodo nulla duis magna. Culpa magna pariatur esse pariatur qui mollit deserunt.\r\n",
  "registered": "2002-07-16T17:12:49 -06:-30",
  "latitude": -24.160585,
  "longitude": -16.899829
}, {
  "id": 3,
  "guid": "6c68e678-515e-4753-b994-73bfe50c8854",
  "isActive": true,
  "balance": "$1,717.00",
  "picture": "http://placehold.it/64x64",
  "age": 20,
  "name": "Riley Santana",
  "gender": "male",
  "company": "Uncorp",
  "position": "guard",
  "sdn_games": 64,
  "sdn_wins": 90,
  "fairplayer": 62,
  "king_of_court": 28,
  "level": "Social",
  "email": "rileysantana@uncorp.com",
  "phone": "+1 (841) 509-2073",
  "address": "982 Highlawn Avenue, Ezel, Wisconsin, 6403",
  "about": "Sint adipisicing laborum nisi nisi proident culpa. Dolor aliqua occaecat adipisicing do sunt sit. Culpa qui magna labore nulla ipsum Lorem et reprehenderit. Officia id laboris amet magna sit aliquip ut proident laboris ea do deserunt. Consequat laboris sit cupidatat sit amet amet officia pariatur aliquip veniam id duis.\r\n",
  "registered": "2003-05-29T19:28:19 -06:-30",
  "latitude": 53.796183,
  "longitude": 64.949194
}, {
  "id": 4,
  "guid": "c4e27dc4-600a-4bcf-bf4f-01beb32f5664",
  "isActive": true,
  "balance": "$1,514.00",
  "picture": "http://placehold.it/64x64",
  "age": 37,
  "name": "Pratt Huber",
  "gender": "male",
  "company": "Hyplex",
  "position": "guard",
  "sdn_games": 44,
  "sdn_wins": 13,
  "fairplayer": 31,
  "king_of_court": 43,
  "level": "Social",
  "email": "pratthuber@hyplex.com",
  "phone": "+1 (947) 452-2549",
  "address": "853 Taylor Street, Forbestown, New Mexico, 5646",
  "about": "Eu excepteur tempor aliqua consectetur incididunt irure commodo nulla et reprehenderit culpa incididunt do dolore. Tempor minim culpa veniam sunt enim tempor duis Lorem adipisicing consequat. Sint excepteur laborum nostrud aliquip elit sunt eu occaecat veniam ut consequat in elit.\r\n",
  "registered": "1991-10-04T22:58:42 -06:-30",
  "latitude": 47.309156,
  "longitude": 170.46992
}, {
  "id": 5,
  "guid": "29d28824-f0ed-438b-ad21-5efa9a6ba529",
  "isActive": true,
  "balance": "$1,848.00",
  "picture": "http://placehold.it/64x64",
  "age": 28,
  "name": "Calhoun Kelly",
  "gender": "male",
  "company": "Geekus",
  "position": "center",
  "sdn_games": 76,
  "sdn_wins": 59,
  "fairplayer": 74,
  "king_of_court": 26,
  "level": "Social",
  "email": "calhounkelly@geekus.com",
  "phone": "+1 (810) 490-3697",
  "address": "544 Franklin Street, Ada, North Carolina, 6576",
  "about": "Officia eu exercitation magna deserunt dolor irure fugiat Lorem incididunt Lorem occaecat consectetur irure excepteur. Commodo deserunt in eu esse tempor est cupidatat adipisicing aliqua. Aliqua id tempor culpa minim ullamco magna proident laborum aute sunt ex magna qui. Duis consectetur eiusmod nisi id id cillum magna irure elit sit dolor nostrud nostrud veniam.\r\n",
  "registered": "1992-10-01T09:31:23 -06:-30",
  "latitude": 23.437352,
  "longitude": 146.305167
}, {
  "id": 6,
  "guid": "e29f1ea0-65e0-4cbf-a210-968093ca36fb",
  "isActive": true,
  "balance": "$2,351.00",
  "picture": "http://placehold.it/64x64",
  "age": 34,
  "name": "Gayle Duran",
  "gender": "female",
  "company": "Geekosis",
  "position": "center",
  "sdn_games": 85,
  "sdn_wins": 95,
  "fairplayer": 20,
  "king_of_court": 96,
  "level": "Social",
  "email": "gayleduran@geekosis.com",
  "phone": "+1 (818) 458-3126",
  "address": "369 Drew Street, Outlook, California, 1367",
  "about": "Sit qui laborum aliqua ipsum mollit ullamco laboris nulla dolore. In laborum irure pariatur in enim excepteur ipsum occaecat labore mollit pariatur ut. Tempor dolore pariatur consequat id nulla quis do.\r\n",
  "registered": "1988-09-08T03:20:58 -06:-30",
  "latitude": -67.123045,
  "longitude": 148.693411
}, {
  "id": 7,
  "guid": "9a3049db-76c1-42a6-9739-c84d07b17e29",
  "isActive": false,
  "balance": "$3,478.00",
  "picture": "http://placehold.it/64x64",
  "age": 38,
  "name": "Willa Whitehead",
  "gender": "female",
  "company": "Fibrodyne",
  "position": "guard",
  "sdn_games": 84,
  "sdn_wins": 55,
  "fairplayer": 90,
  "king_of_court": 45,
  "level": "Social",
  "email": "willawhitehead@fibrodyne.com",
  "phone": "+1 (992) 490-3690",
  "address": "997 Amber Street, Efland, Kansas, 6120",
  "about": "Irure veniam dolor quis eu dolor ipsum cillum exercitation. Ex in elit dolore aliqua sunt occaecat cillum est proident. Reprehenderit elit reprehenderit tempor nulla cupidatat cupidatat amet cillum consequat nisi excepteur enim qui. Excepteur aliquip incididunt ullamco eu magna. Ut culpa irure officia pariatur magna anim. Non sunt consectetur elit culpa consectetur ullamco cupidatat amet consectetur.\r\n",
  "registered": "1991-03-14T14:25:06 -06:-30",
  "latitude": 12.936528,
  "longitude": -99.005212
}, {
  "id": 8,
  "guid": "3288e191-d3d4-475a-983c-2962ca3fc704",
  "isActive": true,
  "balance": "$1,062.00",
  "picture": "http://placehold.it/64x64",
  "age": 40,
  "name": "Delaney Freeman",
  "gender": "male",
  "company": "Tingles",
  "position": "guard",
  "sdn_games": 92,
  "sdn_wins": 69,
  "fairplayer": 30,
  "king_of_court": 80,
  "level": "Social",
  "email": "delaneyfreeman@tingles.com",
  "phone": "+1 (864) 415-3073",
  "address": "261 Debevoise Avenue, Castleton, Hawaii, 7745",
  "about": "Adipisicing nostrud ad do do ipsum velit ea pariatur in ullamco velit. Irure non amet pariatur irure exercitation magna nostrud Lorem dolor. Laborum laboris irure esse dolore incididunt cillum incididunt eu ex nulla do.\r\n",
  "registered": "2005-02-15T09:50:41 -06:-30",
  "latitude": -6.869415,
  "longitude": 63.709534
}, {
  "id": 9,
  "guid": "10fbd317-2aab-4ce2-8276-f9c8f5468651",
  "isActive": true,
  "balance": "$2,837.00",
  "picture": "http://placehold.it/64x64",
  "age": 38,
  "name": "Morales Rollins",
  "gender": "male",
  "company": "Apexia",
  "position": "center",
  "sdn_games": 24,
  "sdn_wins": 17,
  "fairplayer": 37,
  "king_of_court": 89,
  "level": "Social",
  "email": "moralesrollins@apexia.com",
  "phone": "+1 (898) 573-3088",
  "address": "475 Butler Place, Haena, Texas, 6677",
  "about": "Aliqua nisi nulla labore aute velit culpa enim. Ullamco eiusmod veniam ut magna anim ea tempor do Lorem sint qui minim esse. Incididunt id qui irure esse laboris. Officia aliquip elit et ea mollit dolore officia in reprehenderit eiusmod duis. Aliquip duis labore incididunt laborum commodo amet.\r\n",
  "registered": "1996-06-18T07:52:12 -06:-30",
  "latitude": -50.073845,
  "longitude": -44.188267
}, {
  "id": 10,
  "guid": "84e7910e-12b4-446b-b834-4a05f2673698",
  "isActive": false,
  "balance": "$1,045.00",
  "picture": "http://placehold.it/64x64",
  "age": 29,
  "name": "Dillard Duncan",
  "gender": "male",
  "company": "Tasmania",
  "position": "guard",
  "sdn_games": 82,
  "sdn_wins": 43,
  "fairplayer": 46,
  "king_of_court": 96,
  "level": "Social",
  "email": "dillardduncan@tasmania.com",
  "phone": "+1 (830) 542-2536",
  "address": "916 Miller Avenue, Sardis, Connecticut, 8176",
  "about": "Ad culpa voluptate excepteur tempor aliqua do mollit culpa nostrud consectetur sint laboris. Aliquip aliqua cillum officia sint eiusmod incididunt. Incididunt Lorem commodo velit elit aute culpa deserunt anim ullamco ea ad esse. Deserunt sint ullamco consectetur voluptate ea eu consequat non. Sunt velit in et do consectetur anim exercitation sit. Voluptate ipsum aliquip sit amet qui cillum labore adipisicing reprehenderit aliquip. Commodo occaecat et qui esse nostrud officia.\r\n",
  "registered": "1994-03-18T07:33:22 -06:-30",
  "latitude": -82.690325,
  "longitude": -173.931704
}, {
  "id": 11,
  "guid": "d0de8fd8-6459-45d8-b2fa-ffce31825f9e",
  "isActive": true,
  "balance": "$3,736.00",
  "picture": "http://placehold.it/64x64",
  "age": 31,
  "name": "Maria Edwards",
  "gender": "female",
  "company": "Eventix",
  "position": "center",
  "sdn_games": 21,
  "sdn_wins": 80,
  "fairplayer": 15,
  "king_of_court": 48,
  "level": "Social",
  "email": "mariaedwards@eventix.com",
  "phone": "+1 (965) 586-3303",
  "address": "247 Berkeley Place, Bethany, Montana, 2667",
  "about": "Exercitation exercitation occaecat eu ea officia laboris id deserunt laborum. Labore aliqua velit Lorem ipsum ad excepteur adipisicing consectetur ipsum velit aliquip amet quis. Quis eiusmod quis aliquip tempor. Aliqua ea laboris elit culpa ullamco Lorem eu Lorem ex magna dolore duis ipsum. Mollit adipisicing dolore consequat aliquip anim officia elit aliquip tempor.\r\n",
  "registered": "2009-02-20T07:36:02 -06:-30",
  "latitude": -42.93888,
  "longitude": -131.223644
}, {
  "id": 12,
  "guid": "e0b31130-0617-4837-8a68-09dc4ce82caf",
  "isActive": true,
  "balance": "$2,878.00",
  "picture": "http://placehold.it/64x64",
  "age": 23,
  "name": "Alexandra Poole",
  "gender": "female",
  "company": "Sensate",
  "position": "guard",
  "sdn_games": 60,
  "sdn_wins": 69,
  "fairplayer": 83,
  "king_of_court": 23,
  "level": "Social",
  "email": "alexandrapoole@sensate.com",
  "phone": "+1 (811) 492-2299",
  "address": "137 Montague Street, Coldiron, Maine, 4004",
  "about": "Exercitation ea consectetur dolore et incididunt ad aliqua exercitation. Amet ea non duis incididunt amet do reprehenderit laboris adipisicing. Elit non laborum quis enim id ex ut aute non. Consectetur esse quis aliquip amet adipisicing elit.\r\n",
  "registered": "2010-02-04T09:01:47 -06:-30",
  "latitude": 64.640322,
  "longitude": 17.510534
}];



angular.module('slamdunk')
.service("playersService", function(){
  'use strict';
  var db = {};
  db.GetAllPlayers = function(successCb, failedCb){
    successCb(players);
  };
  return db;
});